[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts=lib/chainlink-brownie-contracts",
    "openzeppelin/contracts/=lib/openzeppelin-contract/contracts/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[invariants]
runs = 128
depth = 128            #number of runs
fail_on_revert = false
